### ISSUE TITLE
[BUG] creating template from cloud image

### ISSUE THREAD

**Issue by lotherk** [danitso/terraform-provider-proxmox#2]
I'm trying to create proxmox template out of a cloud init image.

proxmox_virtual_environment_file.cloud_image is beeing created but proxmox_virtual_environment_vm.template fails with

```
proxmox_virtual_environment_vm.template: Creating...

Error: cp: cannot stat '/template/iso/focal-server-cloudimg-amd64.img': No such file or directory


  on template.tf line 6, in resource "proxmox_virtual_environment_vm" "template":
   6: resource "proxmox_virtual_environment_vm" "template" {


```
The file does exist on the filesystem (nfs storage). PVE Webinterface shows this error:
```
TASK ERROR: unable to create VM 2040 - storage 'local-lvm' does not exist
```

I also have to set pool_id in the template or it fails with

```

Error: Received an HTTP 400 response - Reason: Parameter verification failed. (pool: invalid format - pool name '' contains invalid characters)

```

I am not using pools. That's why I added your example to my config. Would be nice to not have to add it, though.

There also is a problem with cloud-config when storage is not local but on nfs. It then fails with

```
Error: Failed to determine the datastore path

  on proxmox_cloud-config.tf line 1, in resource "proxmox_virtual_environment_file" "cloud_config":
   1: resource "proxmox_virtual_environment_file" "cloud_config" {


```
I am using a proxmox cluster with nfs storage. It seems that most of the problems are storage related. My resources are as follows:

```

resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "${element(data.proxmox_virtual_environment_datastores.fs02.datastore_ids, index(data.proxmox_virtual_environment_datastores.fs02.datastore_ids, "nfs"))}"
  node_name    = "fs02"

  source_raw {
    # ....
    file_name = "terraform-cloud-config.yml"
  }
}


resource "proxmox_virtual_environment_pool" "example" {
  comment = "Managed by Terraform"
  pool_id = "terraform-provider-proxmox-example"
}

resource "proxmox_virtual_environment_vm" "template" {
  agent {
    enabled = true
  }

  description = "Managed by Terraform"

  disk {
    datastore_id = "nfs"
    file_id      = "${proxmox_virtual_environment_file.cloud_image.id}"
  }

  initialization {
    # ...
  }

  name = "terraform-template"

  network_device {}

  node_name = "fs02"

  operating_system {
    type = "l26"
  }

  pool_id = "${proxmox_virtual_environment_pool.example.id}"

  serial_device {}

  template = true
  vm_id    = 2040
}

resource "proxmox_virtual_environment_file" "cloud_image" {
  content_type = "iso"
  datastore_id = "nfs"
  node_name    = "fs02"

  source_file {
    path = "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
  }
}

resource "proxmox_virtual_environment_vm" "abc" {
        count = 1

        name = "xyz"

        cpu {
                cores = 2
                type = "host"
        }

        memory {
                dedicated = 4096
        }

        network_device {
                bridge = "vmbr80"
        }

        node_name = "pve0${count.index + 1}"

        operating_system {
                type = "l26"
        }

        clone {
                node_name = "fs02"
                vm_id = proxmox_virtual_environment_vm.template.id
        }

}

```

**Comment by danitso-dp** [comment]
I'll take a look at it and get back to you

**Comment by danitso-dp** [comment]
Can you post the contents of the /etc/pve/storage.cfg file on the node? Just replace any parts you find sensitive with "abcd" or similar.

**Comment by lotherk** [comment]
Hi @danitso-dp, thanks for getting back at me. I was away for a few days.

Here's the storage.cfg:
```
dir: local
        path /var/lib/vz
        content snippets,vztmpl,iso,images,rootdir
        maxfiles 0

nfs: nfs
        export /export/pve
        path /mnt/pve/nfs
        server a.b.c.d
        content snippets,vztmpl,backup,rootdir,iso,images
        maxfiles 1
```

I made some changes in the code (hardcoded parts, changing cloud-init from local-lvm: to nfs:) and things started to work then.

**Comment by danitso-dp** [comment]
Hi @lotherk,

Sorry for the late reply. I've pushed an initial fix for the issue, which will hopefully resolve the issue you're experiencing.

**Comment by luhahn** [comment]
Hi  @danitso-dp 

It seems, that this bug is still existing, it least i was having problems with the same issue today. However i recently played around with your provider and added a few commits to my fork.

I fixed the init bug for cloned vms and also removed the hard coded local-lvm value (already testet on our cluster)

I Added a new resource to modify existing vms where you're able to:
- move an existing disk
- resize an existing disk
- reboot the virtual machine 

Let me know if you're interested I'd like to create a Pull Request for this :)

**Comment by danitso-dp** [comment]
Hi @luhahn 

Any contributions are welcome, especially the initialization fix as this is most likely affecting other users.

When it comes to resizing existing disks, I've been planning to add support for this using the existing resource and then support resource imports. However, do create a pull request for the mentioned features so we can discuss it further.

**Comment by danitso-dp** [comment]
Hi @luhahn 

I've pushed the initial cloud-init fix by adding a datastore_id argument. This should be very similar to your fix but follows the same naming convention as the rest of the provider (datastore_id instead of storage).

I'll look into adding support for resource imports sometime this month but I'll most likely release v0.3.0 based on the current code as long as the datastore issue is fixed.

@lotherk any chance you'll have time to test the latest changes?

**Comment by luhahn** [comment]
Hi @danitso-dp 

I'll be on vacation till 16.03.2020 after that i'll test your initialization fix (if lotherk hasn't done it till then) and will create a pull request without the init fix. Then we can discuss any issues with the request. I can also work the disk reresizing into your existing resource if you want to. However this will be done after I'll be back.

**Comment by luhahn** [comment]
@danitso-dp I just tested your current master regarding the init fix and can confirm it now works for us using the new datastore_id variable.

(lotherk and I are working on the same environment)

**Comment by danitso-dp** [comment]
@luhahn That's great to hear. If it's alright with you, I'll close this issue and prepare to release v0.3.0. We can then look into the features you mentioned you had worked on and try to get them ready for v0.4.0.

**Comment by luhahn** [comment]
@danitso-dp it is fine to close this issue. I've opened a PR for further discussion on the mentioned features
